### ISSUE TITLE
No error handling for trying to create accounts that already exist

### ISSUE THREAD

**Issue by bdwalker93** [kfatehi/dva#7]
There is just an "Internal Server Error"

**Comment by bdwalker93** [comment]
Same with not using a valid email address

**Comment by kfatehi** [comment]
relevant line: https://github.com/kfatehi/dva/blob/master/src/server/routes/index.js#L26

you can pass a function to `catch` -- by passing in the funciton `next` i am effectively not giving a shit about the error, but you can always pass a function that looks at the error (first argument into the `catch` callback) and then use express methods to return errors. you can even render an error template or
